### ISSUE TITLE
Invalid yml in Bitrise library

### ISSUE THREAD

**Issue by pilvikala** [sonifex/bitrise-step-onesignal-create-push#1]
The step definition is broken in Bitrise library because the `toolkit` entry is specified twice in the root of the document.

The first occurence is at 

https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/onesignal-create-push/0.0.1/step.yml#L27

and the second is at 

https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/onesignal-create-push/0.0.1/step.yml#L34

You could fix this by correcting your `step.yml` and submitting the new version. Here's the stuff that needs to change:

https://github.com/sonifex/bitrise-step-onesignal-create-push/blob/master/step.yml#L47

```yml
toolkit:
    bash:
    entry_file: step.sh
```

Should be:

```yml
toolkit:
  bash:
    entry_file: step.sh
```
